#!/usr/bin/env python3
#===============================================================================
# File Name    : map_snps.py
# Description  : This script takes in a folder containing all gff's generated by prokka (<samplename>.gff) and a folder of all snp gff's (<samplename>_snps.gff) generated by snippy and maps SNPs to annotations. It outputs a file containing the sample name, SNP start, SNP end, Prokka row, and SNippy row for each matching SNP.
# Usage        : python map_snps.py snippy_directory prokka_directory output_directory
# Author       : Lindsey Hall, hall.l.r@wustl.edu
# Created      : 230808
#===============================================================================
import os
import sys
import re
import pandas as pd
import warnings
import multiprocessing

# Function to parse GFF files and extract relevant information including the entire row
def parse_gff(gff_file):
    annotations = {}
    with open(gff_file, 'r') as f:
        for line in f:
            line = line.strip()
            if not line.startswith("#"):
                parts = line.split('\t')
                start = int(parts[3])
                end = int(parts[4])
                annotations[(start, end)] = (line, parts)  # Store the entire row
    return annotations

# Function to match SNP positions with annotations
def match_snps_with_annotations(snippy_gff, bakta_gff):
    snippy_annotations = parse_gff(snippy_gff)
    bakta_annotations = parse_gff(bakta_gff)
    matches = []

    for snp_start, snp_end in snippy_annotations:
        for annotation_start, annotation_end in bakta_annotations:
            if annotation_start <= snp_start <= annotation_end:
                snippy_row = snippy_annotations[(snp_start, snp_end)]
                bakta_row = bakta_annotations[(annotation_start, annotation_end)]
                matches.append(((snp_start, snp_end), prokka_row, snippy_row))
                break  # Break the loop after finding the first match
    
    return matches

def analyze_sample(snippy_file, snippy_dir, bakta_dir, output_dir):
    sample_name = snippy_file.replace("_snps.gff", "")
    print("Analyzing", sample_name)
    
    snippy_gff_file = os.path.join(snippy_dir, snippy_file)
    bakta_gff_file = os.path.join(bakta_dir, sample_name + ".gff3")
    
    if os.path.exists(bakta_gff_file):
        matches = match_snps_with_annotations(snippy_gff_file, bakta_gff_file)
        print("\tNumber of matches:", len(matches))
        
        # Create dataframe for the sample
        df_data = []
        for match in matches:
            snp_start, snp_end = match[0]
            bakta_row = match[1][0]
            snippy_row = match[2][0]
            df_data.append({"Sample": sample_name, "SNP_Start": snp_start, "SNP_End": snp_end, "Bakta_Row": bakta_row, "SNippy_Row": snippy_row})
        
        # Create and return a dataframe
        df = pd.DataFrame(df_data)
        output_file = os.path.join(output_dir, f"mapped_snps_{sample_name}.csv")
        df.to_csv(output_file, index=False)
        print(f"Matching results for {sample_name} saved to '{output_file}'")
        return df

def main(snippy_dir, bakta_dir, output_dir):
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=FutureWarning)
        
       	sample_files = [snippy_file for snippy_file in os.listdir(snippy_dir) if snippy_file.endswith("_snps.gff")]
        sample_dfs = {}

        for snippy_file in sample_files:
            df = analyze_sample(snippy_file, snippy_dir, bakta_dir, output_dir)
            sample_name = df["Sample"].iloc[0]
            sample_dfs[sample_name] = df

    return sample_dfs

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python map_snps.py snippy_directory prokka_directory output_directory")
    else:
	snippy_directory = sys.argv[1]
        bakta_directory = sys.argv[2]
        output_directory = sys.argv[3]
        sample_dfs = main(snippy_directory, prokka_directory, output_directory)
        
       	print("All sample processing completed.")
